import streamlit as st
from streamlit_lottie import st_lottie 
import json
import requests

def app():
    
    st.title("Parameters Used For Prediction")

    
    left_column,right_column=st.columns(2)

    
    # text_animation_pairs = [
    #     ("Body Mass Index", "A value that allows you to assess the degree of correspondence between a person's mass and his height, and thereby indirectly judge whether the mass is insufficient, normal or excessive. It is important in determining the indications for the need for treatment.", "https://lottie.host/567ba04b-5955-4da3-a026-71a943fc9b1e/5SKtR4N452.json"),
    #     ("Smoking", "Smoking is a major risk factor for cardiovascular disease. When smoke from a cigarette is inhaled, the reaction of the cardiovascular system immediately follows: within one minute, the heart rate begins to rise, increasing by 30% within ten minutes of smoking. The bad habit also increases blood pressure, fibrinogen and platelet levels, making blood clots more likely.", "https://lottie.host/83aaf87c-7572-423f-b288-7587e791bfed/amwv5dVeJP.json"),
    #     ("Alcohol Drinking", "Alcohol causes not only temporary disturbances in the functioning of the heart, but also permanent ones. Heart pain after alcohol is not the only health problem associated with alcohol consumption. \nChronic heavy drinking can lead to high blood pressure, irregular heart rhythms (arrhythmias), cardiomyopathy (weakening of the heart muscle), and an increased risk of heart failure. Additionally, alcohol abuse can raise triglyceride levels and contribute to the development of atherosclerosis (hardening and narrowing of the arteries), leading to an increased risk of heart attacks and strokes. Moderation is key, as moderate alcohol consumption, particularly of red wine, has been associated with some cardiovascular benefits, but excessive drinking poses substantial risks to heart health.", "https://lottie.host/c30e0f22-d9a7-468d-8066-7ae1ddf95263/NWTTWNeTBq.json"),
    #     ("Stroke","Stroke and heart disease are intricately connected, sharing many of the same risk factors and underlying mechanisms. Conditions like hypertension, diabetes, high cholesterol, and atrial fibrillation can increase the risk of both stroke and heart disease. A stroke occurs when blood flow to part of the brain is interrupted, often due to a blockage in a blood vessel (ischemic stroke) or a rupture of a blood vessel (hemorrhagic stroke). Many of the same factors that lead to heart disease, such as atherosclerosis and blood clots, can also contribute to strokes, highlighting the importance of comprehensive cardiovascular care to prevent both conditions.","https://lottie.host/0dea1d7d-7986-4c98-9398-6bd228b98534/U9MdmrijnT.json"),
    #     ("Physical Health","Physical health and heart disease are deeply intertwined, with poor physical health significantly increasing the risk of developing heart disease. Regular physical activity plays a crucial role in maintaining a healthy cardiovascular system by helping to control weight, lower blood pressure, improve cholesterol levels, and reduce the risk of diabetes. Conversely, a sedentary lifestyle contributes to obesity, hypertension, and other risk factors for heart disease. Additionally, physical fitness can enhance the heart's ability to pump blood efficiently and improve overall cardiovascular function. Prioritizing physical health through regular exercise, a balanced diet, and maintaining a healthy weight can greatly reduce the risk of heart disease and promote overall well-being.","https://lottie.host/5a565079-a0f2-4ae2-a8d9-dabff2f8e3a8/l4mGOQ9Ix5.json"),
    #     ("Mental Health","Mental health is an often overlooked aspect of health as a whole. Chronic stress, anxiety, depression, and social isolation have been associated with an increased risk of developing heart disease. These mental health challenges can lead to unhealthy coping mechanisms such as smoking, overeating, or excessive alcohol consumption, all of which are detrimental to cardiovascular health. Moreover, stress hormones like cortisol can contribute to inflammation, high blood pressure, and other risk factors for heart disease. Prioritizing mental well-being through stress management techniques, seeking social support, and addressing mental health concerns through therapy or counseling can significantly lower the risk of heart conditions and promote overall physical health in the long term.","https://lottie.host/958fe567-1733-4443-980f-54f9ecfaf824/9HdZOxNhmQ.json"),
    #     ("Race","The link between someone's racial background and the risk of heart disease is complex and multifaceted. Research has consistently shown disparities in heart disease prevalence and outcomes among different racial and ethnic groups. Factors such as socioeconomic status, access to healthcare, cultural influences, and genetic predispositions all contribute to these disparities. For example, African Americans, Hispanic Americans, and Native Americans tend to have higher rates of heart disease compared to white Americans, often due to a combination of genetic factors and higher prevalence of risk factors like hypertension, obesity, and diabetes within these communities. Addressing these disparities requires a comprehensive approach that includes improving access to quality healthcare, addressing social determinants of health, and promoting culturally sensitive prevention and treatment strategies.","https://lottie.host/591ce9d8-a014-4eed-b866-9bce4b28aa3b/NxDdKpCb4E.json"),
    #     ("Diabetes","Diabetes and heart disease often go hand in hand, forming a complex relationship that can significantly impact a person's health. \nIndividuals with diabetes, especially type 2 diabetes, are at a higher risk of developing heart disease compared to those without diabetes. This heightened risk is largely due to several interrelated factors, including insulin resistance, high blood sugar levels, dyslipidemia (abnormal lipid levels), hypertension, and obesity, all of which are common in diabetes. These factors can lead to the development of atherosclerosis, a condition characterized by the buildup of plaque in the arteries, increasing the risk of heart attacks, strokes, and other cardiovascular complications. Managing diabetes effectively through lifestyle modifications, medication, and regular medical care is essential in reducing the risk of heart disease in individuals with diabetes.","https://lottie.host/7a23ddd6-2320-40e3-b20d-e97d94081f87/3pL2b6EzHk.json"),
    #     ("Physical activity","Physical activity plays a crucial role in reducing the risk of heart disease. Regular exercise helps to improve cardiovascular health by strengthening the heart muscle, lowering blood pressure, improving cholesterol levels, and enhancing circulation. Additionally, physical activity helps to maintain a healthy weight and reduce the risk of obesity, a major risk factor for heart disease. Engaging in regular aerobic exercises such as brisk walking, jogging, swimming, or cycling can also improve insulin sensitivity and reduce the risk of developing type 2 diabetes, further lowering the risk of heart disease. Overall, incorporating regular physical activity into one's lifestyle is a cornerstone of heart disease prevention and promotes overall cardiovascular health.","https://lottie.host/7f2a642d-8356-478c-b284-e04d7a0397cc/IrAzZ9tgBE.json"),
    #     ("number of hours slept","Lack of sufficient sleep has been linked to an increased risk of heart conditions. Chronic sleep deprivation can disrupt the body's internal rhythms, leading to elevated levels of stress hormones, inflammation, and increased blood pressure, all of which are risk factors for heart disease. Additionally, inadequate sleep can negatively impact glucose metabolism and insulin sensitivity, contributing to the development of diabetes, another significant risk factor for heart disease. \nConversely, excessive sleep, although less common than sleep deprivation, can also be detrimental to heart health. Studies have shown that sleeping for more than 9 hours per night on a regular basis may increase the risk of heart disease and cardiovascular events. Excessive sleep duration has been associated with obesity, diabetes, depression, and other conditions that are known risk factors for heart disease. While individual sleep needs vary, maintaining a consistent and appropriate sleep duration is important for overall heart health.","https://lottie.host/bf404ed7-80b2-4c60-85b9-843e1f346d22/0iftqGwTeM.json"),
    #     ("Asthma","The link between asthma and heart disease is increasingly recognized, although the mechanisms behind their association are still being explored. People with asthma have a higher risk of developing cardiovascular conditions such as hypertension, coronary artery disease, and heart failure compared to those without asthma. Chronic inflammation, a hallmark of asthma, is believed to play a significant role in the development of cardiovascular complications. Additionally, medications commonly used to manage asthma, such as corticosteroids, may contribute to cardiovascular risk factors like hypertension and dyslipidemia. Furthermore, asthma-related factors such as reduced physical activity and poor lung function may indirectly impact heart health. Close monitoring of cardiovascular risk factors and comprehensive management of both asthma and associated conditions are essential to mitigate the risk of heart disease in individuals with asthma.","https://lottie.host/1c9884c8-4a1d-49dc-be42-5c4a94528bb1/OfeCLHvls6.json"),
    #     ("Kidney disease","The link between kidney disease and heart disease is well-established and bidirectional, meaning each condition can contribute to the other's progression. Chronic kidney disease (CKD) is a known risk factor for the development and progression of cardiovascular disease, including coronary artery disease, heart failure, and arrhythmias. CKD often leads to hypertension, fluid overload, electrolyte imbalances, and inflammation, all of which contribute to cardiovascular complications. Conversely, heart disease can also contribute to the progression of kidney disease by reducing renal blood flow, causing renal artery stenosis, and exacerbating fluid retention. Additionally, conditions such as diabetes and hypertension, which are major risk factors for both kidney disease and heart disease, further underscore the close relationship between these two organ systems. Managing risk factors, regular monitoring, and early intervention are crucial in reducing the risk of cardiovascular events in individuals with kidney disease.","https://lottie.host/09382e3c-c3c6-4707-a09d-91f8d910e8fa/mDwOczrUUS.json"),
    #     ("Skin Cancer","Cardiac metastasis of skin cancer can have serious implications for heart health. Skin cancer, particularly melanoma, can spread to distant organs, including the heart, through the bloodstream or lymphatic system. When cancer cells infiltrate the heart tissue, they can interfere with its normal function, leading to conditions such as pericardial effusion (accumulation of fluid around the heart), cardiac tamponade (compression of the heart due to fluid buildup), or even metastatic tumors within the heart muscle. These complications can impair cardiac function and lead to symptoms such as chest pain, shortness of breath, and palpitations, potentially resulting in heart failure or other life-threatening cardiovascular events. Early detection and management of cardiac metastasis are crucial in preserving heart function and overall health in patients with advanced skin cancer.","https://lottie.host/74fd504d-cb31-4c36-b5e1-66fc444d3328/OlQGlU7dIj.json")

    # ]

    
    # for subheader, text, animation_url in text_animation_pairs:
    #     with left_column:
    #         st.subheader(subheader)
    #         st.write(text)
    #     with right_column:
    #         display_lottie_animation(animation_url)
    with left_column:
        st.markdown(
    """
    <style>
    /* Customize the background color of the +/- buttons */
    .stMarkdown > div{
        text-align:justify;
    }
    </style>
    """,
    unsafe_allow_html=True
)
        st.subheader('Body Mass Index')
        st.write("A value that allows you to assess the degree of correspondence between a person's mass and his height, and thereby indirectly judge whether the mass is insufficient, normal or excessive. It is important in determining the indications for the need for treatment.")
        st.subheader('Smoking')
        st.write('Smoking is a major risk factor for cardiovascular disease. When smoke from a cigarette is inhaled, the reaction of the cardiovascular system immediately follows: within one minute, the heart rate begins to rise, increasing by 30% within ten minutes of smoking. The bad habit also increases blood pressure, fibrinogen and platelet levels, making blood clots more likely.')
        st.subheader('Alcohol')
        st.write('Alcohol causes not only temporary disturbances in the functioning of the heart, but also permanent ones. Heart pain after alcohol is not the only health problem associated with alcohol consumption. \nChronic heavy drinking can lead to high blood pressure, irregular heart rhythms (arrhythmias), cardiomyopathy (weakening of the heart muscle), and an increased risk of heart failure. Additionally, alcohol abuse can raise triglyceride levels and contribute to the development of atherosclerosis (hardening and narrowing of the arteries), leading to an increased risk of heart attacks and strokes.')
        st.subheader('Stroke')
        st.write("Stroke and heart disease are intricately connected, sharing many of the same risk factors and underlying mechanisms. Conditions like hypertension, diabetes, high cholesterol, and atrial fibrillation can increase the risk of both stroke and heart disease. A stroke occurs when blood flow to part of the brain is interrupted, often due to a blockage in a blood vessel (ischemic stroke) or a rupture of a blood vessel (hemorrhagic stroke). Many of the same factors that lead to heart disease, such as atherosclerosis and blood clots, can also contribute to strokes, highlighting the importance of comprehensive cardiovascular care to prevent both conditions.") 
        st.subheader('Physical Health')
        st.write("Physical health and heart disease are deeply intertwined, with poor physical health significantly increasing the risk of developing heart disease. Regular physical activity plays a crucial role in maintaining a healthy cardiovascular system by helping to control weight, lower blood pressure, improve cholesterol levels, and reduce the risk of diabetes. Conversely, a sedentary lifestyle contributes to obesity, hypertension, and other risk factors for heart disease. Additionally, physical fitness can enhance the heart's ability to pump blood efficiently and improve overall cardiovascular function. Prioritizing physical health through regular exercise, a balanced diet, and maintaining a healthy weight can greatly reduce the risk of heart disease and promote overall well-being.")
        st.subheader('Mental Health')
        st.write("Mental health is an often overlooked aspect of health as a whole. Chronic stress, anxiety, depression, and social isolation have been associated with an increased risk of developing heart disease. These mental health challenges can lead to unhealthy coping mechanisms such as smoking, overeating, or excessive alcohol consumption, all of which are detrimental to cardiovascular health. Moreover, stress hormones like cortisol can contribute to inflammation, high blood pressure, and other risk factors for heart disease. Prioritizing mental well-being through stress management techniques, seeking social support, and addressing mental health concerns through therapy or counseling can significantly lower the risk of heart conditions and promote overall physical health in the long term.")
        st.subheader('Race')
        st.write("The link between someone's racial background and the risk of heart disease is complex and multifaceted. Research has consistently shown disparities in heart disease prevalence and outcomes among different racial and ethnic groups. Factors such as socioeconomic status, access to healthcare, cultural influences, and genetic predispositions all contribute to these disparities. For example, African Americans, Hispanic Americans, and Native Americans tend to have higher rates of heart disease compared to white Americans, often due to a combination of genetic factors and higher prevalence of risk factors like hypertension, obesity, and diabetes within these communities. Addressing these disparities requires a comprehensive approach that includes improving access to quality healthcare, addressing social determinants of health, and promoting culturally sensitive prevention and treatment strategies.")
        st.subheader('Diabetes')
        st.write("Diabetes and heart disease often go hand in hand, forming a complex relationship that can significantly impact a person's health. Individuals with diabetes, especially type 2 diabetes, are at a higher risk of developing heart disease compared to those without diabetes. This heightened risk is largely due to several interrelated factors, including insulin resistance, high blood sugar levels, dyslipidemia (abnormal lipid levels), hypertension, and obesity, all of which are common in diabetes. These factors can lead to the development of atherosclerosis, a condition characterized by the buildup of plaque in the arteries, increasing the risk of heart attacks, strokes, and other cardiovascular complications. Managing diabetes effectively through lifestyle modifications, medication, and regular medical care is essential in reducing the risk of heart disease in individuals with diabetes.")
        #st.image("https://lottie.host/7a23ddd6-2320-40e3-b20d-e97d94081f87/3pL2b6EzHk.json")

        st.subheader('Exercise')
        st.write("Physical activity plays a crucial role in reducing the risk of heart disease. Regular exercise helps to improve cardiovascular health by strengthening the heart muscle, lowering blood pressure, improving cholesterol levels, and enhancing circulation. Additionally, physical activity helps to maintain a healthy weight and reduce the risk of obesity, a major risk factor for heart disease. Engaging in regular aerobic exercises such as brisk walking, jogging, swimming, or cycling can also improve insulin sensitivity and reduce the risk of developing type 2 diabetes, further lowering the risk of heart disease. Overall, incorporating regular physical activity into one's lifestyle is a cornerstone of heart disease prevention and promotes overall cardiovascular health.")
        #st.image("https://lottie.host/7f2a642d-8356-478c-b284-e04d7a0397cc/IrAzZ9tgBE.json")

        st.subheader('Sleep Time')
        st.write("Lack of sufficient sleep has been linked to an increased risk of heart conditions. Chronic sleep deprivation can disrupt the body's internal rhythms, leading to elevated levels of stress hormones, inflammation, and increased blood pressure, all of which are risk factors for heart disease. Additionally, inadequate sleep can negatively impact glucose metabolism and insulin sensitivity, contributing to the development of diabetes, another significant risk factor for heart disease. Conversely, excessive sleep, although less common than sleep deprivation, can also be detrimental to heart health. Studies have shown that sleeping for more than 9 hours per night on a regular basis may increase the risk of heart disease and cardiovascular events. Excessive sleep duration has been associated with obesity, diabetes, depression, and other conditions that are known risk factors for heart disease. While individual sleep needs vary, maintaining a consistent and appropriate sleep duration is important for overall heart health.")
        #st.image("https://lottie.host/bf404ed7-80b2-4c60-85b9-843e1f346d22/0iftqGwTeM.json")

        st.subheader('Asthma')
        st.write("The link between asthma and heart disease is increasingly recognized, although the mechanisms behind their association are still being explored. People with asthma have a higher risk of developing cardiovascular conditions such as hypertension, coronary artery disease, and heart failure compared to those without asthma. Chronic inflammation, a hallmark of asthma, is believed to play a significant role in the development of cardiovascular complications. Additionally, medications commonly used to manage asthma, such as corticosteroids, may contribute to cardiovascular risk factors like hypertension and dyslipidemia. Furthermore, asthma-related factors such as reduced physical activity and poor lung function may indirectly impact heart health. Close monitoring of cardiovascular risk factors and comprehensive management of both asthma and associated conditions are essential to mitigate the risk of heart disease in individuals with asthma.")
        #st.image("https://lottie.host/1c9884c8-4a1d-49dc-be42-5c4a94528bb1/OfeCLHvls6.json")

        st.subheader('Kidney Disease')
        st.write("The link between kidney disease and heart disease is well-established and bidirectional, meaning each condition can contribute to the other's progression. Chronic kidney disease (CKD) is a known risk factor for the development and progression of cardiovascular disease, including coronary artery disease, heart failure, and arrhythmias. CKD often leads to hypertension, fluid overload, electrolyte imbalances, and inflammation, all of which contribute to cardiovascular complications. Conversely, heart disease can also contribute to the progression of kidney disease by reducing renal blood flow, causing renal artery stenosis, and exacerbating fluid retention. Additionally, conditions such as diabetes and hypertension, which are major risk factors for both kidney disease and heart disease, further underscore the close relationship between these two organ systems. Managing risk factors, regular monitoring, and early intervention are crucial in reducing the risk of cardiovascular events in individuals with kidney disease.")
        #st.image("https://lottie.host/09382e3c-c3c6-4707-a09d-91f8d910e8fa/mDwOczrUUS.json")

        st.subheader('Skin Cancer')
        st.write("Cardiac metastasis of skin cancer can have serious implications for heart health. Skin cancer, particularly melanoma, can spread to distant organs, including the heart, through the bloodstream or lymphatic system. When cancer cells infiltrate the heart tissue, they can interfere with its normal function, leading to conditions such as pericardial effusion (accumulation of fluid around the heart), cardiac tamponade (compression of the heart due to fluid buildup), or even metastatic tumors within the heart muscle. These complications can impair cardiac function and lead to symptoms such as chest pain, shortness of breath, and palpitations, potentially resulting in heart failure or other life-threatening cardiovascular events. Early detection and management of cardiac metastasis are crucial in preserving heart function and overall health in patients with advanced skin cancer.")
        #st.image("https://lottie.host/74fd504d-cb31-4c36-b5e1-66fc444d3328/OlQGlU7dIj.json")


    with right_column:
        st.write('')
        st.write('')
        display_lottie_animation('https://lottie.host/567ba04b-5955-4da3-a026-71a943fc9b1e/5SKtR4N452.json')
        st.write('')
        st.write('')
        display_lottie_animation('https://lottie.host/83aaf87c-7572-423f-b288-7587e791bfed/amwv5dVeJP.json')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        display_lottie_animation('https://lottie.host/c30e0f22-d9a7-468d-8066-7ae1ddf95263/NWTTWNeTBq.json')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        display_lottie_animation('https://lottie.host/0dea1d7d-7986-4c98-9398-6bd228b98534/U9MdmrijnT.json')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        display_lottie_animation('https://lottie.host/5a565079-a0f2-4ae2-a8d9-dabff2f8e3a8/l4mGOQ9Ix5.json')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        display_lottie_animation('https://lottie.host/958fe567-1733-4443-980f-54f9ecfaf824/9HdZOxNhmQ.json')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        display_lottie_animation('https://lottie.host/591ce9d8-a014-4eed-b866-9bce4b28aa3b/NxDdKpCb4E.json')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        display_lottie_animation('https://lottie.host/7a23ddd6-2320-40e3-b20d-e97d94081f87/3pL2b6EzHk.json')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        
        display_lottie_animation('https://lottie.host/7f2a642d-8356-478c-b284-e04d7a0397cc/IrAzZ9tgBE.json')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        
        display_lottie_animation('https://lottie.host/bf404ed7-80b2-4c60-85b9-843e1f346d22/0iftqGwTeM.json')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        display_lottie_animation('https://lottie.host/1c9884c8-4a1d-49dc-be42-5c4a94528bb1/OfeCLHvls6.json')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        display_lottie_animation('https://lottie.host/09382e3c-c3c6-4707-a09d-91f8d910e8fa/mDwOczrUUS.json')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        st.write('')
        display_lottie_animation('https://lottie.host/f8995551-2c0b-48d1-8b9b-970f42461398/iwgDfFZlbc.json')


    

def display_lottie_animation(url):
    url_json = {}
    response = requests.get(url)
    if response.status_code == 200:
        url_json = response.json()
    else:
        print("Error fetching animation from URL:", url)
    st_lottie(url_json, width=200, height=200)

# if __name__ == "__main__":
#     main()